### PR TITLE
better formatted

### PR DESCRIPTION
**Pull request by semprathlon**
code blocks completed

### CODE REVIEW

**Comment by semprathlon** [comment]
What I forgot is that double $ is required to label a LaTeX formula here...

**Comment by CodeFalling** [comment]
Seems still not work somewhere in my mobile phone,maybe you could install `jekyll` and test this site in local.

**Comment by SimplyY** [comment]
666 学弟来当线上负责人吧，这个博客系统你已经玩的这么6了，md排版比我还厉害

**Comment by CodeFalling** [comment]
我已经把@semprathlon添加到operator组了但是不知道为什么还是没有权限，等我回去的时候看看

**Pull request merged**
